# Generated by Django 4.1.5 on 2023-04-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='desc',
        ),
        migrations.DeleteModel(
            name='PostVersion',
        ),
    ]
