# Generated by Django 4.1.5 on 2023-04-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_rename_content_post_desc_delete_postversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commit.post')),
            ],
        ),
    ]
