# Generated by Django 4.1.5 on 2023-04-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0004_post_version_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_version',
            name='version',
        ),
    ]
