# Generated by Django 4.1.5 on 2023-04-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0005_remove_post_version_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_version',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
