# Generated by Django 4.1.5 on 2023-04-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0008_post_content_alter_version_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
