# Generated by Django 4.1.5 on 2023-04-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0009_remove_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='content',
            new_name='desc',
        ),
    ]
